sudo: false
language: python

env:
  - PYTHON=3.5 PANDAS=0.19.2
  - PYTHON=3.6 PANDAS='0.24.0'
  - PYTHON=3.7 PANDAS='master'
  - PYTHON=3.8 PANDAS='master' COVERAGE='true'
  - PYTHON=3.9 PANDAS='master' LINT='true'

before_install:
  - echo "before_install"
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - df -h
  - pwd
  - uname -a
  - git --version
  - git tag

install:
  - ci/install_travis.sh

script:
  - source activate test-environment && pytest -s -v --cov=pandas_msgpack --cov-report xml:/tmp/pytest-cov.xml pandas_msgpack
  - if [ $COVERAGE ]; then source activate test-environment && codecov ; fi
  - if [ $LINT ]; then source activate test-environment && flake8 pandas_msgpack ; fi
